// src/components/ColorInputOutput.vue
<script setup lang="ts">
import { useSelectedColorStore } from "@/stores/selectedColor";
import { valid } from "chroma-js";
import { storeToRefs } from "pinia";

const store = useSelectedColorStore();

const { inputColor, selectedColor } = storeToRefs(store);

const updateInputColor = () => {
  if (isValidColor(inputColor.value)) {
    store.updateInputColor(inputColor.value);
  }
};

const isValidColor = (color: string) => {
  return valid(color);
};
</script>

<template>
  <v-container>
    <v-row justify="center">
      <v-col sm="12" md="8">
        <v-card class="p-3 elevation-8">
          <v-form
            class="color-form d-flex justify-content-between align-items-center gap-lg-4 flex-lg-row flex-column"
          >
            <v-text-field
              v-model="inputColor"
              label="Arbitrary CSS Color"
              required
              @keyup="updateInputColor()"
              hide-details="true"
            ></v-text-field>

            <v-icon
              icon="mdi-arrow-right"
              class="d-none d-lg-block overflow-visible"
            />
            <v-icon icon="mdi-arrow-down" class="d-lg-none mb-2" />

            <v-text-field
              v-model="selectedColor"
              label="Material Design Color"
              required
              hide-details="true"
            ></v-text-field>
          </v-form>
        </v-card>
      </v-col>
    </v-row>
  </v-container>
</template>

<style lang="scss" scoped>
.v-card {
  background: rgb(var(--v-theme-secondary));
}

.color-form {
  .v-input {
    width: 100%;
  }
}
</style>

// src/app/color-input-output/color-input-output.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { FormControl, FormGroup, Validators } from '@angular/forms';
import * as chroma from 'chroma-js';
import * as IMask from 'imask';

@Component({
  selector: 'app-color-input-output',
  templateUrl: './color-input-output.component.html',
  styleUrls: ['./color-input-output.component.scss'],
})
export class ColorInputOutputComponent implements OnInit {
  colorForm: FormGroup;
  colorPatternMask!: IMask.MaskedDynamic;

  private _selectedColor: string | undefined;

  @Input()
  set selectedColor(value: string | undefined) {
    this._selectedColor = value;
    this.setColor();
  }

  get selectedColor() {
    return this._selectedColor;
  }

  @Output()
  convert = new EventEmitter<string>();

  constructor() {
    this.colorForm = new FormGroup({
      colorInput: new FormControl('', [Validators.required]),
      colorOutput: new FormControl('', [Validators.required]),
    });
  }

  ngOnInit(): void {
    this.setInputMask();
  }

  /**
   * If a color has been entered via the color picker store the value also in the input element
   */
  onChangeColorPicker(event: Event): void {
    const color = (event.target as HTMLInputElement).value;
    this.colorForm.get('colorInput')?.setValue(color);
    this.triggerConvert();
  }

  triggerConvert(): void {
    if (this.colorForm.valid) {
      this.convert.emit(this.colorForm.value.colorInput);
    }
  }

  /**
   * Get color value of the form for the color picker
   */
  getColorFormValue(): string | undefined {
    const color = this.colorForm.get('colorInput')?.value;
    if (color && chroma.valid(color)) {
      return chroma(color).hex();
    }
    return undefined;
  }

  private setColor() {
    const color = this.selectedColor ?? '#FFFFFF';
    this.colorForm.get('colorOutput')?.setValue(color);
  }

  private setInputMask() {
    this.colorPatternMask = IMask.createMask({
      mask: [
        {
          mask: 'RGB,RGB,RGB',
          blocks: {
            RGB: {
              mask: IMask.MaskedRange,
              from: 0,
              to: 255,
            },
          },
        },
        {
          mask: /^#[0-9a-f]{0,6}$/i,
        },
      ],
    });
  }
}

<div class="color-input row d-flex justify-content-center py-3">
  <div class="col-12 col-lg-8">
    <mat-card class="p-3 mat-elevation-z0">
      <form
        [formGroup]="colorForm"
        (keyup)="triggerConvert()"
        class="color-form d-flex justify-content-between align-items-center gap-lg-4 align-items-lg-baseline flex-lg-row flex-column"
      >
        <mat-form-field class="color-form-field">
          <mat-label>Arbitrary CSS Color</mat-label>
          <input
            id="color-input"
            matInput
            cdkFocusInitial
            formControlName="colorInput"
            [imask]="colorPatternMask"
            required
          />
          <mat-error
            id="required-error"
            *ngIf="colorForm.get('color')?.hasError('required')"
            >Please enter a color!</mat-error
          >
          <input
            type="color"
            matSuffix
            [value]="getColorFormValue()"
            (change)="onChangeColorPicker($event)"
          />
          <mat-hint> Enter either HEX or RGB color values. </mat-hint>
        </mat-form-field>

        <mat-icon class="d-none d-lg-block"> arrow_forward </mat-icon>
        <mat-icon class="d-lg-none mb-2"> arrow_downward </mat-icon>

        <mat-form-field class="color-form-field">
          <mat-label>Material Design Color</mat-label>
          <input
            id="color-output"
            matInput
            formControlName="colorOutput"
            readonly
          />
        </mat-form-field>
      </form>
    </mat-card>
  </div>
</div>
